### ISSUE TITLE
Container name is shortened after latest update

### ISSUE THREAD

**Issue by anebz** [pyro2927/AWS_SSO_Containers#29]
Hi, after the last update when I am in a container, I see the container name in the URL field is now much shorter. Before I don't remember if it showed the whole container name, but now I count only 14 characters. Many of my accounts have the same beginning so now I can't immediately see which account it is, it would be nice if this was configurable.
thanks!

**Comment by acahill** [comment]
This is just to do with the container name displayed in the location bar, right? The container tabs dialog still seems to have the full name. I reverted to v1.8 and the display was the same, so it might be an issue/change with the Container Tabs addon instead. It looks like that might have changed in version 8.1.3: https://github.com/mozilla/multi-account-containers/releases/tag/8.1.3

**Comment by senilio** [comment]
I "fixed" it by doing the following:

1. Go to `about:config` - set `toolkit.legacyUserProfileCustomizations.stylesheets` to `true`
2. Go to `about:support` - get path under "Profile Folder"
3. Create folder "$PROFILE/chrome"
4. Create file "$PROFILE/chrome/userChrome.css" with content:
```
#userContext-label {
    max-width: unset !important;
}
```
5. Restart Firefox

Tested with Firefox 130.0.1. The full container name is visible in the address bar again.

**Comment by pyro2927** [comment]
@acahill's PR has been merged and pushed with 1.10

**Comment by acahill** [comment]
Sorry, I've confused things by linking this issue to #28. That PR does resolve the issue #26, but this issue is still open. That other change might help a bit because you can use it to make the tab name shorter, but the location bar name limit is still an issue.

Either way it's not really anything to do with this addon at all, since the limit is an issue with https://github.com/mozilla/multi-account-containers. But since @senilio has a handy workaround it could be documented in the README

**Comment by senilio** [comment]
Some digging shows the breaking change is in Firefox itself, so it's not an issue in multi-account-containers either. 
[This](https://github.com/mozilla/multi-account-containers/issues/2641#issuecomment-2174374989) led me to [this](https://support.mozilla.org/tn/questions/1450135) which shows that the real issue is [this line](https://searchfox.org/mozilla-release/source/browser/components/contextualidentity/content/usercontext.css#111), added in Firefox 127.0 😄

**Comment by acahill** [comment]
Hey, nice find! Anyway IMO there's no need to reopen this, the workaround seems pretty good.
