### ISSUE TITLE
Control over the container colors and icons

### ISSUE THREAD

**Issue by tonglil** [pyro2927/AWS_SSO_Containers#4]
As a big user of containers, I would like to limit the extension to creating containers for AWS with a specific icon only (and any color).

Not necessarily, but perhaps also limit to creating contains with a specific color (and any icon).

Or both, a specific icon and color combo for all containers.

I know this has the potential to "confuse" open tabs, but I accept that.

**Comment by david-macias** [comment]
+1 on this request. Being able to create either the first and only container or use the same container that is customized with your preferred icon and color would be nice.

**Comment by callumgare** [comment]
I'd also find this very handy! One way I could see this working is that you can set a colour and/or icon if the account name/roll matched a substring (or maybe a regex for advanced users).

Our account names are all in the format `$APPNAME-$ENV` so in my case I'd set a bunch of rules to match each $ENV we have and apply colour based on that, then another set of rules to match different app names and apply and icon based on that. For that to work multiple rules would have to match and be applied (one to match then env and set a colour, and one to match the app name and set the icon), rather than only applying the first rule that matches.

**Comment by revdandom** [comment]
In Firefox, I can modify the container tab settings to adjust color.   We'll see if the changes stick.

**Comment by pyro2927** [comment]
@tonglil, once a container is created, it is loaded on future SSO calls based on name. While it's not exactly the flow you describe, you can create customize a container after it is created (both color and icon), and it will be honored going forward.

What @revdandom said, they should stick.

**Comment by pyro2927** [comment]
@tonglil if there is something that "Manage Containers" doesn't give you, let me know.
![image](https://github.com/pyro2927/AWS_SSO_Containers/assets/39943/e654aa08-86b0-4176-bf6b-e00a738f925d)

**Comment by david-macias** [comment]
I vote for this issue to be closed and maybe the documentation updated to let everyone know how they can customize their container after it's initially created.

**Comment by pyro2927** [comment]
Added some notes in the README to try and help
